name: Deploy Staging 🚀

on:
  push:
    branches:
      - master

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH for Server Login
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}

      - name: Test SSH Connection to Server
        run: ssh -o StrictHostKeyChecking=no -T ${{ secrets.SSH_USER_NAME_STAGING }}@${{ secrets.SSH_HOST_STAGING }} || exit 1

      - name: Run deployment script on staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          script: |
            set -e
            MYAPP_STG_PATH="/home/ubuntu/pacmailstaging"
            if [ -d "$MYAPP_STG_PATH" ]; then
              cd $MYAPP_STG_PATH
              sudo docker-compose down --remove-orphans --timeout 60 || true
              git pull origin master
            else
              mkdir -p $MYAPP_STG_PATH
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              git clone ${{ secrets.GIT_URL }} $MYAPP_STG_PATH
              cd $MYAPP_STG_PATH
            fi
            touch .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
            sudo docker-compose --env-file .env up --build --detach

      - name: Wait for the application to start
        run: sleep 30

      - name: Test Hit Endpoint
        run: |
          curl -f http://${{ secrets.STG_URL }}:3000 || (
            echo "Fetching docker logs for backend and frontend..."
            sudo docker logs backend
            sudo docker logs frontend
            exit 1
          )
